Solution 79 of substitution-cipher, ratio 0.0 of 1.00 of tests passed. W&B: https://wandb.ai/codex-for-psb/seidr-telo-psb2-llama3-run6/runs/vm0p3ltr Prompt: Traceback (most recent call last):   File "/global/D1/homes/anastasiia/research/secureIT/nl2ml-codex/venv_poetry/li b/python3.11/site-packages/programlib/programs/1fcd1677-41a4-4e24-9ecf-fce74bb85 76e.py", line 14, in <module>     print(substitution_cipher((cipher_map, message)))           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ TypeError: substitution_cipher() missing 1 required positional argument: 'messag e'