Solution 12 of substitution-cipher, ratio 1.0 of 1.00 of tests passed. W&B: https://wandb.ai/codex-for-psb/seidr-telo-psb2-llama3-run3/runs/5fs892st Prompt: Traceback (most recent call last):   File "/global/D1/homes/anastasiia/research/secureIT/nl2ml-codex/venv_poetry/li b/python3.11/site-packages/programlib/programs/ba6ad63e-af5f-4137-a8b6-8da0508c9 c82.py", line 15, in <module>     substitution_cipher( TypeError: substitution_cipher() missing 1 required positional argument: 'messag e'